server:
  port: 9090
  servlet:
    context-path: /hospital-api

spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name: hospital
  datasource:
    name: test
    url:  jdbc:mysql://localhost:3306/hospital
    username: root
    password: root
    driver:
      class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update